# Generated by Django 5.1.7 on 2025-03-07 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_incentive', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentStage',
            fields=[
                ('stage_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('day_count', models.IntegerField()),
                ('percentage', models.IntegerField()),
                ('created_date', models.DateField()),
                ('created_user', models.CharField(max_length=50)),
                ('updated_date', models.DateField(blank=True, null=True)),
                ('updated_user', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'payment_stage',
            },
        ),
    ]
